# Generated by Django 6.0.1 on 2026-02-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_slug_5e91f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_categor_4083ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_is_feat_19b203_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_name_9ff0a3_idx",
            old_name="products_name_6f9890_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_is_acti_ca4d9a_idx",
            old_name="products_is_acti_cb485f_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_price_9b1a5f_idx",
            old_name="products_price_fe467e_idx",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="products_pr_created_bce1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name", "is_active"], name="products_pr_name_59cb5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "price"], name="products_pr_categor_47b724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="products_pr_is_acti_645007_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
    ]
