# Generated by Django 6.0.1 on 2026-02-15 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price at order time",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_sku",
            field=models.CharField(
                blank=True,
                help_text="Product SKU at order time",
                max_length=100,
                null=True,
            ),
        ),
    ]
