# Generated by Django 6.0.1 on 2026-02-15 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_alter_orderitem_price_alter_orderitem_product_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        help_text="Stripe Payment Intent ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stripe_client_secret",
                    models.CharField(
                        blank=True,
                        help_text="Stripe client secret for frontend",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="Payment currency (ISO code)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        blank=True,
                        help_text="Payment method type (card, bank, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of card/account",
                        max_length=4,
                    ),
                ),
                (
                    "failure_message",
                    models.TextField(
                        blank=True, help_text="Error message if payment failed"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when payment succeeded",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Order associated with this payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order"], name="payments_pa_order_i_1d1c93_idx"
                    ),
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="payments_pa_stripe__6fe52c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="payments_pa_status_7ad4af_idx"
                    ),
                ],
            },
        ),
    ]
