# Generated by Django 6.0.1 on 2026-01-27 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        help_text="User email manzili",
                        max_length=254,
                        unique=True,
                        verbose_name="Email manzil",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Ism"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, null=True, verbose_name="Familiya"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="+998901234567 formatda",
                        max_length=20,
                        null=True,
                        verbose_name="Telefon raqam",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="To'liq manzil",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Shahar"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="Uzbekistan",
                        max_length=100,
                        null=True,
                        verbose_name="Mamlakat",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Pochta indeksi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="User login qila oladimi?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Admin panelga kirish xuquqi",
                        verbose_name="Staff status",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Barcha ruxsatlar",
                        verbose_name="Superuser status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Ro'yxatdan o'tgan sana",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi kirish"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
                "db_table": "users",
                "ordering": ["-date_joined"],
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(
                        fields=["date_joined"], name="users_date_jo_0c802f_idx"
                    ),
                ],
            },
        ),
    ]
